server:
  port: 8888
fastdfs:
  charset: UTF-8
spring:
  application:
    name: localhost
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/fileDB